services:
  webapp:
    build:
      context: .
    ports:
      - "80:3000"
    command: [ "npm", "run", "${NPM_SCRIPT}" ]
    labels:
      com.datadoghq.ad.logs: "[{\"source\": \"nodejs\", \"service\": \"${SERVICE_NAME}\"}]"
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWD}@${DB_HOSTNAME}:5432/${DB_NAME}"

  datadog_agent:
    image: public.ecr.aws/datadog/agent
    hostname: datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:datadog-agent"
      DD_SITE: "datadoghq.com"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_CONTAINER_ENV_AS_TAGS: '{"NODE_ENV":"env"}'
      DD_API_KEY: "${DD_API_KEY}"
